"""JWT cookie auth for the web UI.

A single shared password (``settings.auth_password``) gates the API. On login a
short-lived HS256 JWT is issued and stored in an HttpOnly cookie. When the
password is empty, auth is disabled (dev convenience) and ``require_auth`` is a
no-op.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets as token_gen
import time
from dataclasses import dataclass
from ipaddress import ip_address, ip_network
from typing import TYPE_CHECKING

import jwt
from fastapi import Request, Security
from fastapi.exceptions import HTTPException
from fastapi.security import APIKeyCookie
from starlette.status import HTTP_401_UNAUTHORIZED

from loreline.logging import get_logger
from loreline.settings import DEFAULT_JWT_SECRET

if TYPE_CHECKING:
    from ipaddress import IPv4Network, IPv6Network

    from loreline.secrets import SecretStore
    from loreline.settings import Settings

log = get_logger(__name__)

COOKIE_NAME = "loreline_token"
_ALGORITHM = "HS256"
_JWT_SECRET_NAME = "_jwt_secret"


def ensure_jwt_secret(settings: Settings, store: SecretStore) -> None:
    """Replace a missing/default JWT secret with a persisted random one.

    Auth integrity rests entirely on this HMAC key; shipping the public default
    would let anyone forge a session cookie. When the secret is unset (empty or
    the built-in default), reuse a previously generated value from the secret
    store, or mint and persist a fresh 32-byte secret.
    """
    if settings.jwt_secret and settings.jwt_secret != DEFAULT_JWT_SECRET:
        return
    existing = store.get(_JWT_SECRET_NAME)
    if existing:
        settings.jwt_secret = existing
        return
    generated = token_gen.token_hex(32)
    store.set(_JWT_SECRET_NAME, generated)
    settings.jwt_secret = generated
    log.warning("auth.jwt_secret.autogenerated")


def auth_enabled(settings: Settings) -> bool:
    """Return True if a password is configured (auth active)."""
    return bool(settings.auth_password)


def _trusted_proxy_networks(settings: Settings) -> list[IPv4Network | IPv6Network]:
    """Parse ``trusted_proxies`` into networks, ignoring (and logging) junk."""
    networks: list[IPv4Network | IPv6Network] = []
    for entry in settings.trusted_proxies.split(","):
        candidate = entry.strip()
        if not candidate:
            continue
        try:
            networks.append(ip_network(candidate, strict=False))
        except ValueError:
            log.warning("auth.trusted_proxy.invalid", entry=candidate)
    return networks


def _peer_is_trusted_proxy(request: Request, settings: Settings) -> bool:
    """Whether this connection's own peer is allowed to speak for the client."""
    client = request.client
    if client is None or not settings.trusted_proxies:
        return False
    try:
        peer = ip_address(client.host)
    except ValueError:
        return False
    return any(peer in network for network in _trusted_proxy_networks(settings))


def client_uses_https(request: Request, settings: Settings) -> bool:
    """Whether the browser's own connection to this app is over TLS.

    The app is reached two ways in the bundled compose stack: straight over
    plain HTTP on the LAN (the primary supported path), and through Caddy,
    which terminates TLS and then speaks plain HTTP to the app on the compose
    network. The request object says ``http`` in both cases, so the login
    cookie would end up either never ``Secure`` or always ``Secure``, and each
    is wrong for one of the two paths.

    ``X-Forwarded-Proto``, which Caddy sets on everything it proxies, is what
    tells them apart - but the app's own port is published on the host as well
    (see docker-compose.yml), so anything on the LAN can reach it directly and
    send that header itself. It is therefore believed only when the connection
    comes from a peer the operator listed in ``LORELINE_TRUSTED_PROXIES``:
    compose sets that to the private range Caddy's container sits in, which a
    LAN client arriving on the published port never appears from. Left empty
    (the default, and every bare-metal install) nothing is trusted and only a
    genuinely HTTPS connection gets a ``Secure`` cookie.

    What is left over is a process on the Docker host itself, which does arrive
    from that range: it can talk its own login response into a ``Secure``
    cookie its browser then refuses to send back over plain HTTP. That is a
    failure of its own login and nobody else's, in the safe direction. The
    dangerous direction, stripping ``Secure`` off a real HTTPS session, is not
    reachable: those requests come through Caddy, which sets the header itself.
    """
    if _peer_is_trusted_proxy(request, settings):
        # Stacked proxies append to the header; the first hop faced the client.
        forwarded = request.headers.get("x-forwarded-proto", "").split(",")[0].strip().lower()
        if forwarded:
            return forwarded == "https"
    return request.url.scheme == "https"


def _password_fingerprint(settings: Settings) -> str:
    """Short digest of the current password, bound into issued tokens.

    The JWT secret doesn't change when the operator rotates the password
    (it's a separate, persisted signing key), so a signature check alone
    can't tell a token issued under the old password from one issued after.
    Binding this fingerprint means changing ``LORELINE_AUTH_PASSWORD`` and
    restarting immediately invalidates every previously-issued cookie,
    instead of leaving them valid for the rest of their TTL (up to 12h).
    """
    return hashlib.sha256(settings.auth_password.encode()).hexdigest()[:16]


def issue_token(settings: Settings) -> str:
    """Issue a signed session JWT."""
    now = int(time.time())
    payload = {
        "sub": "loreline",
        "iat": now,
        "exp": now + settings.jwt_ttl_seconds,
        "pwd": _password_fingerprint(settings),
    }
    return jwt.encode(payload, settings.jwt_secret, algorithm=_ALGORITHM)  # pyright: ignore[reportUnknownMemberType]


def verify_token(token: str, settings: Settings) -> bool:
    """Return True if ``token`` is valid, unexpired, and matches the current password."""
    try:
        payload = jwt.decode(token, settings.jwt_secret, algorithms=[_ALGORITHM])  # pyright: ignore[reportUnknownMemberType]
    except jwt.PyJWTError:
        return False
    return payload.get("pwd") == _password_fingerprint(settings)  # pyright: ignore[reportUnknownMemberType]


def verify_password(password: str, settings: Settings) -> bool:
    """Constant-time check of the shared password."""
    expected = settings.auth_password
    if not expected:
        return False
    return hmac.compare_digest(password, expected)


@dataclass(slots=True)
class _Attempts:
    count: int = 0
    locked_until: float = 0.0


class LoginRateLimiter:
    """Per-client-IP login backoff.

    A single shared password with no rate limiting is a free brute-force
    target. State lives in memory, keyed by client IP rather than globally,
    so one bad actor probing the password can't lock the real users at the
    table out of their own device. Not persisted across restarts - that's
    fine, a restart is a rare enough reset vector for a LAN device.
    """

    def __init__(self, *, max_attempts: int = 5, lockout_seconds: float = 30.0) -> None:
        self._max_attempts = max_attempts
        self._lockout_seconds = lockout_seconds
        self._attempts: dict[str, _Attempts] = {}

    def allowed(self, key: str) -> bool:
        """Return True if ``key`` may attempt a login right now."""
        entry = self._attempts.get(key)
        if entry is None or not entry.locked_until:
            return True
        if entry.locked_until <= time.monotonic():
            del self._attempts[key]
            return True
        return False

    def record_failure(self, key: str) -> None:
        entry = self._attempts.setdefault(key, _Attempts())
        entry.count += 1
        if entry.count >= self._max_attempts:
            entry.locked_until = time.monotonic() + self._lockout_seconds

    def record_success(self, key: str) -> None:
        self._attempts.pop(key, None)


#: Declares the session cookie to OpenAPI so every route behind ``require_auth``
#: says so in the schema, instead of the schema claiming the whole API is open.
#: ``auto_error=False`` keeps the scheme purely descriptive: a missing cookie
#: returns ``None`` and ``require_auth`` decides, so the 401 body and the
#: auth-disabled no-op stay exactly as they were.
session_cookie = APIKeyCookie(
    name=COOKIE_NAME,
    scheme_name="sessionCookie",
    auto_error=False,
    description=(
        "Session JWT set by `POST /api/auth/login`. The cookie is HttpOnly, so "
        "pasting a value into this dialog does nothing: browsers drop the "
        "`Cookie` header Swagger UI would set from it. To use `Try it out`, run "
        "`POST /api/auth/login` from this page first (or log into the app in the "
        "same browser); the cookie is then sent automatically. Outside a browser, "
        "send the cookie yourself, e.g. `curl -c jar -X POST .../api/auth/login "
        "-d '{\"password\":\"...\"}' -H 'content-type: application/json'` then "
        "`curl -b jar .../api/session`. When no password is configured auth is "
        "off entirely and the cookie is not required."
    ),
)


def require_auth(request: Request, token: str | None = Security(session_cookie)) -> None:
    """FastAPI dependency enforcing a valid auth cookie when auth is enabled."""
    settings: Settings = request.app.state.ctx.settings
    if not auth_enabled(settings):
        return
    if not token or not verify_token(token, settings):
        raise HTTPException(status_code=HTTP_401_UNAUTHORIZED, detail="authentication required")
