#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Runs on the Loreline box, from the checkout (the directory holding
# docker-compose.yml). Needs tailscale installed and logged in, sudo and curl.
# It changes exactly one thing on the box, and this undoes it:
#   sudo tailscale serve --https=443 off
#
# Why: browsers hand out the microphone only in a secure context, so
# "This device's microphone" stays greyed out on http://<lan-ip>/ until the
# box is reachable over HTTPS with a certificate every device trusts. Tailscale
# issues one for the box's *.ts.net name with nothing to install on the laptop
# or the phone. README, "Recording from a laptop", is the long version.

TOTAL_STAGES=7

# cert_domain prints the *.ts.net name Tailscale will issue a certificate for,
# or nothing while HTTPS certificates are still off for the tailnet.
cert_domain() {
  local json
  json=$(tailscale status --json 2>/dev/null) || return 0
  if command -v python3 >/dev/null 2>&1; then
    printf '%s' "$json" | python3 -c '
import json, sys
d = json.load(sys.stdin)
c = d.get("CertDomains") or []
print(c[0] if c else "")' 2>/dev/null || true
  else
    printf '%s' "$json" | grep -o '[a-z0-9-]*\.[a-z0-9-]*\.ts\.net' | head -n1 || true
  fi
}

banner "Tailscale HTTPS for Loreline: let the browser be the microphone"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Check this box"
say "This wizard runs on the Loreline box, inside the Loreline checkout."
if [[ ! -f docker-compose.yml ]]; then
  warn "No docker-compose.yml here. cd to the checkout (usually /opt/loreline) and re-run."
  exit 1
fi
if ! command -v tailscale >/dev/null 2>&1; then
  warn "tailscale is not installed on this box. Install it first: https://tailscale.com/download/linux"
  exit 1
fi
if ! tailscale status >/dev/null 2>&1; then
  warn "tailscale is installed but not connected. Run: sudo tailscale up"
  exit 1
fi
PORT=$(_existing LORELINE_PORT || true)
PORT="${PORT:-8000}"
if curl -fsS -m 5 "http://127.0.0.1:${PORT}/api/system/livez" >/dev/null 2>&1; then
  say "Loreline answers on 127.0.0.1:${PORT}."
else
  warn "Nothing answers on http://127.0.0.1:${PORT}/api/system/livez."
  warn "Start the stack first (docker compose up -d), or fix LORELINE_PORT in .env, then re-run."
  exit 1
fi
note "tailscale is connected and the app is up. Nothing has been changed yet."
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Tailscale admin console: MagicDNS, then HTTPS Certificates"
say "Do this on your laptop, not on this box. Without both toggles no certificate"
say "is ever issued, and the browser keeps refusing the microphone with no hint why."
step "Open https://login.tailscale.com/admin/dns"
step "Under MagicDNS: enable it, if it is not already on."
step "Under HTTPS Certificates: enable HTTPS."
note "Order matters: MagicDNS first, then HTTPS Certificates."
pause "Done both? Press Enter to verify from this box"
until [[ -n "$(cert_domain)" ]]; do
  warn "This box does not report a certificate name yet. Give it a few seconds, check both toggles,"
  pause "then press Enter to check again"
done
say "HTTPS certificates are enabled for this tailnet."
pause

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "This box's HTTPS name"
TS_DEFAULT=$(cert_domain)
say "Tailscale will issue a certificate for: ${TS_DEFAULT}"
printf '  %sName to use%s [%s]: ' "$BOLD" "$RESET" "$TS_DEFAULT"
read -r TS_NAME || true
TS_NAME="${TS_NAME:-$TS_DEFAULT}"
if [[ -z "$TS_NAME" ]]; then
  warn "No name. Re-run once the admin console shows HTTPS certificates enabled."
  exit 1
fi
say "Using https://${TS_NAME}/"
pause

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Point the HTTPS name at Loreline"
say "This runs on the box, as root:"
say "  sudo tailscale serve --bg --https=443 http://127.0.0.1:${PORT}"
note "It proxies https://${TS_NAME}/ to the app's published port. Re-running it is safe:"
note "it replaces the previous setting rather than adding to it."
if confirm "Run it now?"; then
  if sudo tailscale serve --bg --https=443 "http://127.0.0.1:${PORT}"; then
    say "Current serve configuration:"
    tailscale serve status || true
  else
    warn "tailscale serve refused. Read its message above, fix the cause, and re-run this wizard."
    exit 1
  fi
else
  warn "Skipped. Run the command above by hand before the next stage."
fi
pause

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Verify over HTTPS, from this box"
say "Asking https://${TS_NAME}/api/system/livez ..."
VERIFIED=""
for attempt in 1 2 3 4 5 6; do
  if out=$(curl -fsS -m 10 "https://${TS_NAME}/api/system/livez" 2>/dev/null) && [[ "$out" == *'"ok"'* ]]; then
    VERIFIED=1
    break
  fi
  if [[ "$attempt" -lt 6 ]]; then
    note "not yet (a first certificate can take up to a minute to be issued), retry ${attempt}/6 in 10 s"
    sleep 10
  fi
done
if [[ -n "$VERIFIED" ]]; then
  say "Loreline answers over HTTPS on its Tailscale name."
else
  warn "No answer over HTTPS yet. The two usual causes:"
  note "  1. The certificate is still being issued. Wait a minute and re-run this wizard; repeating it is safe."
  note "  2. Something else on this box owns the tailnet's port 443. Move to another port:"
  note "       sudo tailscale serve --https=443 off"
  note "       sudo tailscale serve --bg --https=8443 http://127.0.0.1:${PORT}"
  note "     and open https://${TS_NAME}:8443/ instead."
fi
pause

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "The Secure cookie: the one setting that fails silently"
say "Behind a TLS proxy the app marks its login cookie Secure only when the proxy's"
say "address is inside LORELINE_TRUSTED_PROXIES. tailscale serve reaches the published"
say "port from the Compose bridge gateway, which docker-compose.yml trusts by default."
if grep -Eq '^[[:space:]]*LORELINE_TRUSTED_PROXIES:[[:space:]]*172\.16\.0\.0/12' docker-compose.yml; then
  say "docker-compose.yml trusts 172.16.0.0/12."
else
  warn "LORELINE_TRUSTED_PROXIES in docker-compose.yml is not the stock 172.16.0.0/12."
  warn "It must include the range tailscale serve arrives from, or an HTTPS login gets a cookie without the Secure flag."
fi
note "If Compose runs on a custom address pool, add that pool to the same setting."
pause

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Record from your laptop"
step "On the laptop, open https://${TS_NAME}/ and sign in."
step "On the Dashboard, pick 'This device's microphone' in the capture card."
step "Allow the microphone when the browser asks; the list of inputs fills in after that."
step "Watch the level meter move, then press Start."
note "Keep that tab open and the lid up for the whole session: a closed lid ends the recording about 45 s later."
note "To undo everything this wizard did:  sudo tailscale serve --https=443 off"
pause "Recording works? Press Enter to finish"

finish
